[email]
app_password = "aupl kqzu pxag hcoi"
notification_recipients = "aaron.bell@bostonmedflight.org, matthew.gibbs@bostonmedflight.org, Mary.Arredondo@bostonmedflight.org"
admin_email = "aaron.e.bell@gmail.com"
